apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      rack: rack0
  bgpInstances:
  - name: "instance-65000"
    localASN: 64513
    localPort: 179
    peers:
    - name: "NXOS"
      peerASN: 64512
      peerAddress: 192.168.52.1/32
      