apiVersion: cilium.io/v2alpha1
kind: BGPPeeringPolicy
metadata:
  name: bgp-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux

  virtualRouters:
    - localASN: 64513
      exportPodCIDR: true
      neighbors:
        - peerAddress: 192.168.52.1/32
          peerASN: 64512