apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
  bgpInstances:
  - name: "instance-65002"
    localASN: 65002
    peers:
    - name: "tor-switch"
      peerASN: 65002
      peerAddress: 192.168.52.1
      peerRefConfig:
        name: "cilium-peer"
      