apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  labels:
    advertise: pod-svc
spec:
  advertisements:
    - advertismentType: "PodCIDR"
      attributes:
        communities:
          standard: ["65002:99"]